### PR TITLE
Compatibility with Symfony 5

### PR DESCRIPTION
**Pull request by ameotoko**
This allows widget to work with Symfony 5

see https://github.com/symfony/symfony/blob/5.x/UPGRADE-5.0.md#eventdispatcher

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
The `composer.json` should be updated accordingly as well. I can help with that later today.

**Comment by aschempp** [comment]
This will make the extension incompatible with Contao 4.4 (which is fine, I'm just saying). That's probably what @fritzmg meant by adjusting the `composer.json`.

**Comment by ameotoko** [comment]
> This will make the extension incompatible with Contao 4.4.

Ok, now I get it about `composer.json`. TBH, I have a very little idea about the whole picture of dependencies etc., comparing to a library developer; I just digged a little, how to bring it back to working state for my projects, did a little testing and decided to share it in my first pull request, instead of opening just another issue 😊

**Comment by qzminski** [comment]
Guess this should be fixed somehow, as on some Contao installations it fails to upload the files. @aschempp can't we have a support for both Symfony 4 and 5 the same time?

**Comment by aschempp** [comment]
> can't we have a support for both Symfony 4 and 5 the same time?

We can, but Contao 4.4 is still on Symfony 3.x as far as I know. And that does not have the contracts 😉

**Comment by fritzmg** [comment]
I am also fine with dropping support for Contao 4.4. We could release it as `3.2.0` so that at least there is a path for further bugfix releases that could potentially be done for 4.4, if really necessary.

**Comment by aschempp** [comment]
Thank you @ameotoko

**Pull request merged**
